version: "3.9"

services:
  chat:
    container_name: chat-service
    build:      
      context: ./Chat
      dockerfile: "WebApi/Dockerfile"    
  
  group:
    container_name: group-service
    build:
      context: ./Group
      dockerfile: "WebApi/Dockerfile"

  identity:
   container_name: identity-service
   build:
     context: ./Identity
     dockerfile: "PresentationLayer/Dockerfile"


  mssql:
    container_name: mssql
    image: mcr.microsoft.com/mssql/server:2022-latest